version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Toronto'
    groups:
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      testing-library:
        patterns:
          - '*testing-library*'
      jest:
        patterns:
          - '*jest*'
      eslint:
        patterns:
          - '@eslint/js'
          - 'eslint'
          - 'typescript-eslint'
      prettier:
        patterns:
          - 'eslint-config-prettier'
          - 'eslint-plugin-prettier'
          - 'prettier'
      next:
        patterns:
          - 'next'
          - 'eslint-config-next'
