version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 15
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Toronto'
    reviewers:
      - 'OleksiiKachan'
    groups:
      typescript-eslint:
        patterns:
          - '*typescript-eslint*'
      eslint:
        patterns:
          - '@eslint/js'
          - 'eslint'
