version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'v4'
    registries:
      - npm-github
    open-pull-requests-limit: 15
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'America/Toronto'
    reviewers:
      - 'OleksiiKachan'
