name: 'Setup environment'
description: 'Setup node and install deps'
inputs:
  NPM_TOKEN:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set node version
      uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: yarn
    - name: Install dependencies
      run: yarn install --immutable --frozen-lockfile
      shell: bash
