version: 2.1

parameters:
  weekly_deployment:
    default: false
    type: boolean

orbs:
  node: circleci/node@5.1.0
  
jobs:
  setup:
    executor: node/default
    working_directory: ~/web
    steps:
      - checkout
      - restore_yarn_cache
      - run:
          name: Install
          command: yarn install --check-files --frozen-lockfile
      - save_yarn_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    executor: node/default
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_build_cache
      - run:
          name: Build
          command: CI=true yarn build
      - save_build_cache
  test:
    executor: node/default
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test
  lint:
    executor: node/default
    working_directory: ~/web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run linter
          command: yarn lint

commands:
  save_yarn_cache:
    steps:
      - save_cache:
          name: Restore Yarn Cache
          key: node-packages-yarn-{{ .Environment.YARN_CACHE_VER }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/web/.cache/yarn
            - ~/web/node_modules
  restore_yarn_cache:
    steps:
      - restore_cache:
          name: Save Yarn Cache
          keys:
            - node-packages-yarn-{{ .Environment.YARN_CACHE_VER }}-{{ checksum "yarn.lock" }}
            - node-packages-yarn-{{ .Environment.YARN_CACHE_VER }}-
  save_build_cache:
    steps:
      - save_cache:
          name: Save Next Build Cache
          key: webpack-build-{{ .Environment.BUILD_CACHE_VER }}-{{ .Revision }}
          paths:
            - ~/web/.next/cache
  restore_build_cache:
    steps:
      - restore_cache:
          name: Restore Next Build Cache
          keys:
            - webpack-build-{{ .Environment.BUILD_CACHE_VER }}-{{ .Revision }}
            - webpack-build-{{ .Environment.BUILD_CACHE_VER }}-

workflows:
  pr:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
